import { ConfigProvider } from "antd";
import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope } from "next/font/google";

import "./globals.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: "./logo-mobile.webp",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${manrope.variable} antialiased`}
      >
        <ConfigProvider
          theme={{
            components: {
              Button: {
                colorPrimary: "#E9021E",
                algorithm: true,
              },
              Menu: {
                itemBg: "transparent",
                itemHoverBg: "#E9021E", 
                itemSelectedColor: "#ffffff",
                colorText:"#ffff",
                popupBg: "#121212",
              },
            },
          }}
        >
          {children}
        </ConfigProvider>
      </body>
    </html>
  );
}
